# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: parent
    source: Parent.CI
    trigger: 
      branches:
      - master


trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: dev
  jobs:
  - deployment: DeployToDev

- stage: stage
  jobs:
  - deployment: DeployToStage
  - deployment: DeployToStage2

- stage: prod
  jobs:
  - deployment: DeployToProd
    environment: 'prod'
    