# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: 'ReleaseAPIParameters'
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    # API documentation https://learn.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-7.0&tabs=HTTP
    curl -X POST https://vsrm.dev.azure.com/CustomerDemos-JL/ElevanceHealth/_apis/Release/releases?api-version=7.1-preview.8 \
      --user '':'$(PAT)' \
      -H "Content-Type: application/json" \
      -H "Accept:application/json" \
      -d {
            "definitionId": 1,
            "manualEnvironments": [
            "Stage 2"
            ],
            "artifacts": [],
            "variables": {},
            "environmentsMetadata": [

            ],
            "properties": {
            }
        }

