# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Trigger conditions:
# - Multiple schedules that will be added/removed based on <>
# - Build artifact is published to artifact feed

trigger:
- release

variables:
- name: 
  value:

pool:
  vmImage: ubuntu-latest

jobs:
- job: 
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo .
  - template: .ado/templates/stg.deploy-template.yml  # Template reference
  - script: echo This step runs after the template's steps.