# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Trigger conditions:
# - Multiple schedules that will be added/removed based on <>
# - Build artifact is published to artifact feed

trigger: none
pr: none
resources:
  pipelines:
    - pipeline: 'BuildArtifact'
      source: 'BuildArtifact'
      trigger:
        branches:
          - main

pool:
  vmImage: ubuntu-latest

jobs:
- job: 
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: '5782de39-7081-4bef-b770-373a26b9f288'
      definition: '23'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      targetPath: '$(Pipeline.Workspace)'

  - script: echo This step runs after the template's steps.